
#server {

    root    /git/mclyne/wordpress/wordpress;
    index   index.php index.html index.htm;

    location ~ \.php$ {

        fastcgi_pass   php;
        fastcgi_index  index.php;
        include        inc/fastcgi.conf;
    }
#}
